-- ============================================================
-- 003 — Message payloads move to object storage
--
-- Postgres keeps a small pointer row per message: who, when, type, read state,
-- and where the payload lives. The payload itself (message text, and the
-- audio/video/zip binaries via the files table) is written to Backblaze B2 or
-- Google Cloud Storage.
--
-- body_preview is a deliberate exception. Storing up to 280 characters inline
-- means the overwhelming majority of chat messages render with zero storage
-- round-trips; only genuinely long messages need the object fetched. The object
-- remains the canonical copy — body_preview is a render cache, never the source
-- of truth.
--
-- The legacy `body` column is kept so messages written before this migration
-- keep displaying. New writes leave it null.
-- ============================================================

alter table public.messages add column if not exists body_provider text;
alter table public.messages add column if not exists body_storage_path text;
alter table public.messages add column if not exists body_preview text;
alter table public.messages add column if not exists body_bytes integer;
alter table public.messages add column if not exists body_truncated boolean not null default false;

-- Async delivery bookkeeping. created_at is "sent"; these track the rest.
alter table public.messages add column if not exists delivered_at timestamptz;
alter table public.messages add column if not exists failed_at timestamptz;
alter table public.messages add column if not exists failure_reason text;

-- Idempotency key generated by the browser before the request leaves. A retry
-- after a dropped connection reuses it, so a flaky network cannot produce
-- duplicate messages — which matters a lot for offline/async sending.
alter table public.messages add column if not exists client_sent_id text;

create unique index if not exists messages_client_sent_id_idx
  on public.messages (client_sent_id)
  where client_sent_id is not null;

-- Unread counts are read on every portal page load; make that an index hit.
create index if not exists messages_unread_idx
  on public.messages (client_id, read_at)
  where read_at is null;

-- Backfill: give pre-existing rows a preview so old threads still render
-- without a storage lookup. Safe to re-run.
update public.messages
   set body_preview = left(body, 280)
 where body_preview is null
   and body is not null;
